const CARD_FRONT_IMAGES = [
  { src: "/images/fronts/1.png" },
  { src: "/images/fronts/2.png" },
  { src: "/images/fronts/3.png" },
  { src: "/images/fronts/4.png" },
  { src: "/images/fronts/5.png" },
  { src: "/images/fronts/6.png" },
  { src: "/images/fronts/7.png" },
  { src: "/images/fronts/8.png" },
  { src: "/images/fronts/9.png" },
  { src: "/images/fronts/10.png" },
  { src: "/images/fronts/11.png" },
  { src: "/images/fronts/12.png" },
  { src: "/images/fronts/13.png" },
  { src: "/images/fronts/14.png" },
  { src: "/images/fronts/15.png" },
  { src: "/images/fronts/16.png" },
  { src: "/images/fronts/17.png" },
  { src: "/images/fronts/18.png" },
  { src: "/images/fronts/19.png" },
  { src: "/images/fronts/20.png" },
  { src: "/images/fronts/21.png" },
  { src: "/images/fronts/22.png" },
  { src: "/images/fronts/23.png" },
  { src: "/images/fronts/24.png" },
  { src: "/images/fronts/25.png" },
  { src: "/images/fronts/26.png" },
  { src: "/images/fronts/27.png" },
  { src: "/images/fronts/28.png" },
  { src: "/images/fronts/29.png" },
  { src: "/images/fronts/30.png" },
  { src: "/images/fronts/31.png" },
  { src: "/images/fronts/32.png" },
  { src: "/images/fronts/33.png" },
  { src: "/images/fronts/34.png" },
  { src: "/images/fronts/35.png" },
  { src: "/images/fronts/36.png" },
];

const CARD_BACK_IMAGES = [
  { src: "/images/backs/1.png" },
  { src: "/images/backs/2.png" },
  { src: "/images/backs/3.png" },
  { src: "/images/backs/4.png" },
  { src: "/images/backs/5.png" },
];

export { CARD_FRONT_IMAGES, CARD_BACK_IMAGES };
